# Generated by Django 3.2.7 on 2021-09-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_page',
        ),
    ]
