# Generated by Django 3.2.7 on 2021-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='flower_image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='flower_title',
            new_name='product_title',
        ),
    ]
