# Generated by Django 3.2.7 on 2021-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210918_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='images/product_images/'),
        ),
    ]
